### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by abdullah-coskun** [bounswe/bounswe2019group1#282]
These requirements should be updated according to the feedback in piazza.

- [x] 1.1.1.1.1.1. 

- [x] 1.1.1.1.1.1.2. 

- [x] 1.1.1.1.1.2. 

- [x] 1.1.1.2.1.

- [x] 1.1.1.3.1.2. 

- [x] 1.1.2.1. 

- [x] 1.1.3.3. 

- [x] 1.1.1.4.3.

- [x] 1.1.5.1. 

- [x] 1.2.1.1. 

- [x] 1.2.2.1. 

- [x] 1.2.2.2. 

- [x] 1.2.2.3.

- [x] 1.2.5.1.1.3.

- [x] 1.2.5.1.2. 

- [x] 1.2.5.1.3.

- [x] 1.2.5.1.4.3

- [x] 1.2.5.1.5.4.1

- [x] 1.2.5.1.5.1.

- [x] 1.2.5.1.5.

- [x] 1.2.5.1.7.1

- [x] 2.1.

- [x] 2.4. 

- [x] 2.4.3.

- [x] 2.4.4. 

- [x] 2.5.1.

- [x] 2.5.2.

**Comment by irem-ustunboyacioglu** [comment]
2.5.1. and 2.5.2. were revised.

**Comment by omertoptas** [comment]
I have updated the following requirements  :

- 1.1.1.1.1.1.
- 1.1.1.1.1.1.2.
- 1.1.1.1.1.2.
- 1.1.1.2.1

by removing the parts about username since we are not implementing a "username" feature in our project. E-mail address of the user is used for login, signup etc. Please check these changes.

**Comment by emirhansarac29** [comment]
Updated requirements:

* 1.1.1.3.1.2
* 1.1.2.1 --> Added Glossary "Common User", since there is a misunderstood about common user requirements which can be actioned by both trader and basic
* 1.1.3.3 --> Removed unnecessary parts
* 1.1.5.1 --> 1.1.5.2 added
* 1.2.1.1 --> will keep that requirement
* 1.2.2.1 --> 1.1.1.5.11 added
* 1.2.2.2 --> ?
* 1.2.2.3
* 1.2.5.1.1.3 --> Depending on the used API those all equipments will get update
* 1.2.5.1.2 --> One Turkish stock should be put e.g. ASELS or KCHOL
* 1.2.5.1.3 --> Hope that exist in used API
* 1.2.5.1.4.3 --> Can't find brant oil, all dots added
* 1.2.5.1.5.4.1 --> Base currency will be specified
* 1.2.5.1.5.1 --> Most common changed to most traded
* 1.2.5.1.5 --> Changed to Parities from Currencies
* 1.2.5.1.7.1 --> Base currency will be specified
* 2.1 --> 2.1.6 added
* 2.4.3 - 2.4.4 --> delete
* 2.4 --> 2.4.3 added

**Comment by omertoptas** [comment]
These requirements are already updated and there is already another issue about updating requirements therefore I am closing this issue.
